# Generated by Django 5.0.4 on 2024-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('licency', 'Licency'), ('vendor', 'Vendor')], default='user', max_length=10),
        ),
    ]
